// Category module extracted from index.html.

(function(){
const MBA_EXAMS=[
 {name:'CAT',why:'Best route for IIMs and many leading B-schools.',forWho:'Students targeting the broad top MBA ecosystem.',pattern:'Computer-based test. Recent pattern has 3 timed sections: VARC, DILR and Quantitative Ability.',subjects:'Verbal Ability & Reading Comprehension (VARC); Data Interpretation & Logical Reasoning (DILR); Quantitative Ability (QA).',syllabus:'Reading comprehension, verbal reasoning, arithmetic, algebra, geometry, number systems, data interpretation and logical reasoning.',marking:'Recent pattern: +3 for a correct answer and −1 for an incorrect MCQ. TITA/non-MCQ answers generally have no negative marking.',sectionMarking:[['VARC','24 questions','72 marks'],['DILR','22 questions','66 marks'],['Quantitative Ability','22 questions','66 marks'],['Total','68 questions','204 marks']],examPattern:'Recent CAT formats have used a total duration of about 120 minutes with separate sectional time limits; question count can vary by year.',note:'Section-wise breakup above uses the recent CAT 2024 pattern as a reference. Verify the current CAT notification because question counts can change by year.'},
 {name:'XAT',why:'Primary route for XLRI and a strong parallel option for national B-schools.',forWho:'Students who want an additional national-level MBA entrance route.',pattern:'Computer-based test with aptitude, decision-making and verbal/quantitative components; GK is typically treated separately.',subjects:'Verbal Ability & Logical Reasoning; Decision Making; Quantitative Ability & Data Interpretation; General Knowledge.',syllabus:'RC and verbal reasoning, business and situational decision making, arithmetic, algebra, geometry, DI, logical reasoning and current affairs/static GK.',marking:'Recent XAT pattern: +1 for a correct answer and −0.25 for an incorrect answer. After the allowed number of skips, an additional −0.10 penalty may apply per extra unattempted question. GK typically has no negative marking.',sectionMarking:[['Verbal Ability & Logical Reasoning','26 approx.','26 marks'],['Decision Making','21 approx.','21 marks'],['Quantitative Ability & DI','28 approx.','28 marks'],['General Knowledge','20 approx.','20 marks (separate from percentile)']],examPattern:'Duration and section structure are announced for each cycle and should be verified from the current XAT bulletin.',note:'Decision Making is the key differentiator and should be explained clearly during counselling.'},
 {name:'NMAT',why:'Flexible MBA route for NMIMS and other participating business schools.',forWho:'Students who value a testing window and score-attempt flexibility.',pattern:'Computer-based adaptive test with three separately timed sections.',subjects:'Language Skills; Quantitative Skills; Logical Reasoning.',syllabus:'Reading comprehension, grammar and vocabulary; arithmetic, algebra, DI and number-based reasoning; analytical and logical reasoning.',marking:'No negative marking in the recent NMAT format. Each section is separately timed and the final score is reported on a scaled-score framework rather than simple raw marks.',sectionMarking:[['Language Skills','36 questions','Scaled score'],['Quantitative Skills','36 questions','Scaled score'],['Logical Reasoning','36 questions','Scaled score'],['Total','108 questions','Scaled score']],examPattern:'Recent NMAT formats have used 3 sections and a total duration of about 108 minutes, with section order selected before the test.',note:'Exact attempts, dates and participating colleges vary by cycle.'},
 {name:'SNAP',why:'Entrance route for Symbiosis institutes and programmes.',forWho:'Students specifically targeting the Symbiosis ecosystem.',pattern:'Computer-based test with English, analytical/logical reasoning and quantitative sections.',subjects:'General English; Analytical & Logical Reasoning; Quantitative, Data Interpretation & Data Sufficiency.',syllabus:'Vocabulary, grammar and comprehension; logical and analytical reasoning; arithmetic, algebra, data interpretation and data sufficiency.',marking:'Recent SNAP pattern: +1 for a correct answer and −0.25 for an incorrect answer.',sectionMarking:[['General English','15 questions','15 marks'],['Analytical & Logical Reasoning','25 questions','25 marks'],['Quantitative, DI & Data Sufficiency','20 questions','20 marks'],['Total','60 questions','60 marks']],examPattern:'Recent SNAP formats have used a 60-minute test with 60 questions across three sections.',note:'Multiple test dates may be offered; verify the current SNAP cycle before counselling.'},
 {name:'CMAT',why:'National management entrance accepted by many AICTE-approved institutions.',forWho:'Students building a broader B-school application portfolio.',pattern:'Computer-based objective test with multiple aptitude sections.',subjects:'Quantitative Technique & Data Interpretation; Logical Reasoning; Language Comprehension; General Awareness; Innovation & Entrepreneurship.',syllabus:'Arithmetic and DI, reasoning, English comprehension, current affairs/general awareness and innovation/entrepreneurship basics.',marking:'Recent CMAT pattern: +4 for a correct answer and −1 for an incorrect answer. Unattempted questions receive 0 marks.',sectionMarking:[['Quantitative Techniques & Data Interpretation','20 questions','80 marks'],['Logical Reasoning','20 questions','80 marks'],['Language Comprehension','20 questions','80 marks'],['General Awareness','20 questions','80 marks'],['Innovation & Entrepreneurship','20 questions','80 marks'],['Total','100 questions','400 marks']],examPattern:'Recent CMAT formats have used 100 questions across 5 sections, with 20 questions per section and a 180-minute duration.',note:'Check the latest NTA information bulletin for current dates and any pattern changes.'},
 {name:'MAT',why:'A flexible route to participating B-schools through multiple sessions.',forWho:'Students who need additional admission pathways beyond CAT/XAT/other major exams.',pattern:'Management aptitude test conducted in scheduled modes/sessions depending on the cycle.',subjects:'Language Comprehension; Intelligence & Critical Reasoning; Mathematical Skills; Data Analysis & Sufficiency; Indian & Global Environment.',syllabus:'English comprehension and vocabulary, logical reasoning, arithmetic and basic mathematics, data analysis and current business/general environment.',marking:'Recent MAT pattern has generally used +1 for a correct answer and a small negative marking (commonly −0.25) for an incorrect answer. Verify the current AIMA bulletin for the active cycle.',sectionMarking:[['Language Comprehension','30 questions','30 marks'],['Intelligence & Critical Reasoning','30 questions','30 marks'],['Mathematical Skills','30 questions','30 marks'],['Data Analysis & Sufficiency','30 questions','30 marks'],['Indian & Global Environment','30 questions','30 marks'],['Total','150 questions','150 marks']],examPattern:'Recent formats have used 150 questions across 5 sections with a total duration around 120 minutes; mode and session availability vary.',note:'Always verify the current AIMA MAT bulletin because schedule and mode can change.'}
];
function mbaSidebar(){
 const s=document.getElementById('sidebar'); if(!s)return;
 const items=['MBA Overview|mba-overview','MBA Exams|mba-exams','Eligibility Checker|mba-eligibility','Cut-offs|mba-cutoffs','Colleges & Admissions|mba-colleges','Exam Comparison|mba-comparison','Results & Success Stories|mba-results'];
 s.innerHTML='<div class="brand"><div class="logo">PW</div><div><div class="mba-sidebar-title">Counsellor Intelligence<br>Dashboard (C.I.D)</div><div class="mba-sidebar-sub">MBA · Management & Business</div></div></div><div class="sidebar-divider"></div><div class="nav-label">MBA MODULES</div><div class="mba-nav-section">'+items.map((x,i)=>{let [a,b]=x.split('|');return '<button class="mba-nav-btn '+(i===0?'active':'')+'" data-mba-target="'+b+'" onclick="mbaOpenModule(\''+b+'\')">'+a+'</button>'}).join('')+'</div><div class="mba-sidebar-home"><button onclick="cidGoHome()">← All Categories</button></div>';
}
function mbaOpenModule(id){
 document.querySelectorAll('.mba-panel').forEach(x=>x.style.display='none');
 const panel=document.getElementById(id); if(panel) panel.style.display='block';
 document.querySelectorAll('.mba-nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.mbaTarget===id));
 window.scrollTo({top:0,behavior:'smooth'});
}
window.mbaOpenModule=mbaOpenModule;
function renderMBA(){
 mbaSidebar(); const r=document.getElementById('pageRoot'); r.innerHTML='<div class="mba-wrap">'
+'<section class="mba-panel mba-overview-panel" id="mba-overview"><div class="mba-hero"><div class="mba-kicker">MBA INTELLIGENCE</div><h1>What do you want to help the student with?</h1><p>Select an option to open the relevant MBA counselling tool. Keeping everything separate makes the workspace faster and easier to use during calls.</p></div><div class="mba-module-grid">'
+'<button class="mba-module" onclick="mbaOpenModule(\'mba-exams\')"><div class="i">🎯</div><h3>MBA Exams</h3><p>CAT, XAT, NMAT, SNAP, CMAT and MAT at a glance.</p><span>Open →</span></button>'
+'<button class="mba-module" onclick="mbaOpenModule(\'mba-eligibility\')"><div class="i">✓</div><h3>Eligibility Checker</h3><p>Check broad exam eligibility from the student profile.</p><span>Open →</span></button>'
+'<button class="mba-module" onclick="mbaOpenModule(\'mba-cutoffs\')"><div class="i">▥</div><h3>Cut-offs</h3><p>Indicative score and percentile guidance.</p><span>Open →</span></button>'
+'<button class="mba-module" onclick="mbaOpenModule(\'mba-colleges\')"><div class="i">🏛️</div><h3>Best Colleges</h3><p>College groups and admission routes.</p><span>Open →</span></button>'
+'<button class="mba-module" onclick="mbaOpenModule(\'mba-comparison\')"><div class="i">⚖️</div><h3>Exam Comparison</h3><p>Compare major MBA exams before recommending a route.</p><span>Open →</span></button>'
+'<button class="mba-module" onclick="mbaOpenModule(\'mba-results\')"><div class="i">🏆</div><h3>Results & Success Stories</h3><p>Reserved for verified PW MBA result data.</p><span>Open →</span></button></div></section>'
+'<section class="mba-section mba-panel" id="mba-exams"><button class="mba-back" onclick="mbaOpenModule(\'mba-overview\')">← Back to MBA Overview</button><h2>MBA Entrance Exams</h2><p class="sub">Select an exam to see why students take it, paper pattern, syllabus, subjects, marking structure and exam pattern.</p><div class="mba-exam-grid">'+MBA_EXAMS.map(e=>'<button class="mba-mini mba-exam-card" onclick="mbaOpenExam(\''+e.name+'\')"><b>'+e.name+'</b><span>'+e.why+'</span><em>View exam details →</em></button>').join('')+'</div></section>'
+'<section class="mba-section mba-panel" id="mba-exam-detail"><button class="mba-back" onclick="mbaOpenModule(\'mba-exams\')">← Back to MBA Exams</button><div id="mbaExamDetailContent"></div></section>'
+'<section class="mba-section mba-panel" id="mba-eligibility"><button class="mba-back" onclick="mbaOpenModule(\'mba-overview\')">← Back to MBA Overview</button><h2>Eligibility Checker</h2><p class="sub">Broad screening only — final eligibility depends on the selected exam and institute.</p><div class="mba-form"><label>Target exam<select id="mbaExam"><option>CAT</option><option>XAT</option><option>NMAT</option><option>SNAP</option><option>CMAT</option><option>MAT</option></select></label><label>Graduation status<select id="mbaGrad"><option value="final">Final year / completed graduation</option><option value="notfinal">Not yet in final year</option></select></label><label>Aggregate percentage / CGPA<input id="mbaScore" placeholder="e.g. 62 or 7.2"></label><label>Category<select id="mbaCat"><option>General</option><option>EWS</option><option>OBC-NCL</option><option>SC</option><option>ST</option><option>PwD</option></select></label></div><button class="mba-btn" onclick="checkMBAEligibility()">Check Eligibility</button><div class="mba-result" id="mbaEligibilityResult">Fill the profile to get a quick counselling read.</div><div class="mba-note">This checker gives a broad route recommendation, not a final admission verdict.</div></section>'
+'<section class="mba-section mba-panel" id="mba-cutoffs"><button class="mba-back" onclick="mbaOpenModule(\'mba-overview\')">← Back to MBA Overview</button><h2>Cut-off guidance</h2><p class="sub">Select an exam to view indicative score / percentile ranges for counselling.</p><div class="mba-cutoff-tabs" id="mbaCutoffTabs"><button class="active" onclick="showMBACutoff(\'CAT\',this)">CAT</button><button onclick="showMBACutoff(\'XAT\',this)">XAT</button><button onclick="showMBACutoff(\'NMAT\',this)">NMAT</button><button onclick="showMBACutoff(\'SNAP\',this)">SNAP</button><button onclick="showMBACutoff(\'CMAT\',this)">CMAT</button><button onclick="showMBACutoff(\'MAT\',this)">MAT</button></div><div id="mbaCutoffContent"></div><div class="mba-info-note"><b>Important:</b> These are indicative counselling bands, not guaranteed admission cut-offs. Actual shortlisting depends on institute, category, profile, sectional requirements and the current admission cycle.</div></section>'
+'<section class="mba-section mba-panel" id="mba-colleges"><button class="mba-back" onclick="mbaOpenModule(\'mba-overview\')">← Back to MBA Overview</button><h2>Best Colleges & admission guide</h2><p class="sub">Counselling should focus on fit, exam route, programme preference, location and career goals — not only brand name.</p><div class="mba-college-grid"><div class="mba-mini"><b>Top IIM ecosystem</b><span>Primarily CAT-based routes. Final selection can include academic profile, work experience, diversity and interview stages.</span></div><div class="mba-mini"><b>Premier private B-schools</b><span>May accept XAT, NMAT, SNAP, CAT or institute-specific combinations.</span></div><div class="mba-mini"><b>Specialised MBA routes</b><span>Shortlist by domain such as finance, marketing, analytics, HR or operations.</span></div></div></section>'
+'<section class="mba-section mba-panel" id="mba-comparison"><button class="mba-back" onclick="mbaOpenModule(\'mba-overview\')">← Back to MBA Overview</button><h2>Exam Comparison</h2><p class="sub">Use this to recommend a multi-exam strategy.</p><table class="mba-table"><thead><tr><th>Exam</th><th>Best for</th><th>Frequency</th><th>Quick counselling note</th></tr></thead><tbody><tr><td>CAT</td><td>IIMs + many top B-schools</td><td>Annual</td><td>Primary route for students targeting the broad top MBA ecosystem.</td></tr><tr><td>XAT</td><td>XLRI + partner institutes</td><td>Annual</td><td>Strong parallel option for national-level MBA aspirants.</td></tr><tr><td>NMAT</td><td>NMIMS + accepting institutes</td><td>Testing window</td><td>Useful where score-attempt flexibility is relevant.</td></tr><tr><td>SNAP</td><td>Symbiosis institutes</td><td>Annual</td><td>Recommended for students targeting the Symbiosis ecosystem.</td></tr><tr><td>CMAT / MAT</td><td>Participating B-schools</td><td>Varies</td><td>Good for broadening the application portfolio.</td></tr></tbody></table></section>'
+'<section class="mba-section mba-panel" id="mba-results"><button class="mba-back" onclick="mbaOpenModule(\'mba-overview\')">← Back to MBA Overview</button><h2>Results & Success Stories</h2><p class="sub">This section is intentionally kept blank until PW MBA result data is added.</p><div class="mba-results-empty"><div style="font-size:30px">🏆</div><b>Result data coming soon</b><p style="margin:8px 0 0">We will add year-wise toppers, colleges and success stories once the verified data is available.</p></div></section>'
+'</div>';
 mbaOpenModule('mba-overview');
}
window.mbaOpenExam=function(name){
 const e=MBA_EXAMS.find(x=>x.name===name); if(!e)return;
 const c=document.getElementById('mbaExamDetailContent');
 c.innerHTML='<div class="mba-exam-head"><div><div class="mba-kicker">MBA EXAM GUIDE</div><h2>'+e.name+'</h2><p>'+e.why+'</p></div></div>'+
 '<div class="mba-detail-grid">'+
 '<div class="mba-detail-card"><h3>Why take this exam?</h3><p>'+e.forWho+'</p></div>'+
 '<div class="mba-detail-card"><h3>Paper pattern</h3><p>'+e.pattern+'</p></div>'+
 '<div class="mba-detail-card"><h3>Subjects / sections</h3><p>'+e.subjects+'</p></div>'+
 '<div class="mba-detail-card"><h3>What to study (syllabus)</h3><p>'+e.syllabus+'</p></div>'+
 '<div class="mba-detail-card"><h3>Marking structure</h3><p>'+e.marking+'</p></div>'+
 (e.sectionMarking?'<div class="mba-detail-card mba-section-marking"><h3>Section-wise marking structure</h3><table class="mba-section-table"><thead><tr><th>Section</th><th>Questions</th><th>Maximum marks</th></tr></thead><tbody>'+e.sectionMarking.map((r,i)=>'<tr class="'+(i===e.sectionMarking.length-1?'total-row':'')+'"><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td></tr>').join('')+'</tbody></table><p class="mba-table-note">Reference pattern shown for counselling. Section-wise question count may change in future CAT cycles.</p></div>':'')+
 '<div class="mba-detail-card"><h3>Exam pattern & duration</h3><p>'+e.examPattern+'</p></div>'+
 '</div><div class="mba-info-note"><b>Counsellor note:</b> '+e.note+'</div>';
 mbaOpenModule('mba-exam-detail');
};
window.showMBACutoff=function(exam,btn){const data={CAT:[['Top IIMs / elite B-schools','98–99.5+','Very high percentile; profile and sectional performance can matter.'],['Strong national B-schools','85–98','Competitive range for many established institutes.'],['Good MBA colleges','70–85','Broader options; evaluate ROI and placements.']],XAT:[['XLRI / top XAT routes','95–99+','Highly competitive range; sectional performance may matter.'],['Strong national B-schools','85–95','Good competitive band for multiple institutes.'],['Broader MBA options','70–85','Institute-specific shortlisting varies.']],NMAT:[['Top NMIMS-style targets','230–235+','Higher scores for the most competitive routes.'],['Strong accepting institutes','210–230','Competitive range for several institutes.'],['Broader accepting options','190–210','Institute cut-offs vary.']],SNAP:[['Top Symbiosis institutes','95–98+','Higher band for competitive programmes.'],['Strong Symbiosis options','85–95','Competitive range across programmes.'],['Broader programme options','70–85','Campus and programme cut-offs can differ.']],CMAT:[['Highly competitive colleges','95–99+','For stronger national-level opportunities.'],['Good MBA colleges','80–95','Wide range of participating institutes.'],['Broader options','60–80','Focus on college quality and ROI.']],MAT:[['Higher-tier MAT colleges','600–700+','Score expectations vary by institute.'],['Good accepting colleges','500–600','Common counselling band for many institutes.'],['Broader options','400–500','Evaluate ROI and placement outcomes carefully.']]};const d=data[exam];if(!d)return;document.querySelectorAll('#mbaCutoffTabs button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');const unit=(exam==='NMAT'||exam==='MAT')?'score':'percentile';const cards=d.map(c=>'<div class="mba-cutoff-card"><h3>'+c[0]+'</h3><div class="mba-cutoff-number">'+c[1]+'</div><div class="mba-cutoff-unit">Indicative '+unit+'</div><p>'+c[2]+'</p></div>').join('');const rows=d.map(c=>'<tr><td>'+c[0]+'</td><td><span class="mba-cutoff-badge">'+c[1]+' '+unit+'</span></td><td>'+c[2]+'</td></tr>').join('');document.getElementById('mbaCutoffContent').innerHTML='<div class="mba-cutoff-summary"><b>'+exam+' cut-off view</b><div style="margin-top:6px;color:#607086">Quick counselling reference — verify latest institute-wise criteria before final guidance.</div></div><div class="mba-cutoff-grid">'+cards+'</div><table class="mba-cutoff-table"><thead><tr><th>College group</th><th>Indicative range</th><th>Counselling guidance</th></tr></thead><tbody>'+rows+'</tbody></table>';};
setTimeout(function(){if(window.showMBACutoff){var b=document.querySelector('#mbaCutoffTabs button');if(b)showMBACutoff('CAT',b);}},0);
window.checkMBAEligibility=function(){const ex=document.getElementById('mbaExam').value,g=document.getElementById('mbaGrad').value,v=parseFloat(document.getElementById('mbaScore').value),out=document.getElementById('mbaEligibilityResult');if(g==='notfinal'){out.innerHTML='<b>Current read:</b> The student is not yet in the final year of graduation. Keep the student in a preparation/awareness route and verify the chosen exam\'s current-year rules before registration.';return;}if(Number.isNaN(v)){out.innerHTML='<b>Current read:</b> Add the aggregate percentage or CGPA for a more useful counselling read.';return;}out.innerHTML='<b>Current read for '+ex+':</b> The student is in the final-year/completed-graduation stage and can proceed to detailed exam-wise eligibility verification. The entered academic score is '+v+'. Final eligibility and admission shortlisting remain institute- and category-specific.';};
function mbaShowDashboard(name){document.body.classList.remove('cid-home-mode');document.body.classList.add('cid-category-mode');const h=document.getElementById('cid-category-home');if(h)h.style.display='none';const b=document.querySelector('.cid-category-topbar');if(b){b.style.display='flex';const l=b.querySelector('.cid-current-category');if(l)l.textContent=name;}const r=document.getElementById('pageRoot');if(r)r.style.display='block';const e=document.getElementById('cid-empty-category');if(e)e.style.display='none';}
function mbaShowHome(){document.body.classList.remove('cid-category-mode');document.body.classList.add('cid-home-mode');const h=document.getElementById('cid-category-home');if(h)h.style.display='block';const b=document.querySelector('.cid-category-topbar');if(b)b.style.display='none';const r=document.getElementById('pageRoot');if(r)r.style.display='none';}
window.cidOpenCategory=function(name){ if(name==='MBA'){mbaShowDashboard(name);renderMBA();return;} if(name==='CSIR-NET'){mbaShowDashboard(name);goTo('csirnet');return;} if(name==='IIT-JAM'){mbaShowDashboard(name);goTo('iitjam');return;} if(name==='UGC-NET'){mbaShowDashboard(name);goTo('ugcnet');return;} mbaShowDashboard(name); const r=document.getElementById('pageRoot');if(r)r.innerHTML='<div class="mba-wrap"><section class="mba-section"><h2>'+name+' Intelligence</h2><p class="sub">This category is currently empty. We will build its details step by step.</p></section></div>'; };
window.cidGoHome=function(){mbaShowHome();};
})();
